[project]
name            = "assignment2"
version         = "0.1.0"
description     = "Add your description here"
readme          = "README.md"
requires-python = ">=3.14"
dependencies    = ["fastavro>=1.12.1", "pandas>=3.0.0"]
